package com.amazon.device.ads;

import com.ironsource.mediationsdk.utils.IronSourceConstants;
import java.util.Arrays;
import java.util.List;

public class DtbConstants {
    static String AAX_HOSTNAME = "aax-us.amazon-adsystem.com";
    static String AAX_ROUTE53_ENABLED_CNAME = "aax.amazon-adsystem.com";
    public static final String ADMOB_HEIGHT_KEY = "amazon_custom_event_height";
    static final long ADMOB_REQUESTID_MAP_CLEAR_INTERVAL = 300000;
    public static final String ADMOB_REQUEST_ID_KEY = "amazon_custom_event_request_id";
    public static final String ADMOB_SLOTGROUP_KEY = "amazon_custom_event_slot_group";
    public static final String ADMOB_SLOTUUID_KEY = "amazon_custom_event_slot_uuid";
    public static final String ADMOB_WIDTH_KEY = "amazon_custom_event_width";
    public static final String ADMOB_iSVIDEO_KEY = "amazon_custom_event_is_video";
    static final String AD_TRACKING_ENABLED = "ad-tracking";
    static final String AMAZON_MOBILE = "amazonmobile";
    public static final String APS_ADAPTER_VERSION = "amazon_custom_event_adapter_version";
    public static final String APS_ADAPTER_VERSION_2 = "2.0";
    static final int APS_ANALYTICS_ADDITIONAL_VALUE_SIZE_LIMIT = 100;
    static final int BID_TIMEOUT = 5000;
    static final List<String> BLACK_LIST = Arrays.asList(new String[]{"status", IronSourceConstants.EVENTS_ERROR_CODE, "instrPixelURL"});
    static final long CONFIG_CHECKIN_INTERVAL = 172800000;
    static final int DTB_BETA = 3;
    static final String DTB_CONFIG_ENDPOINT = "mads.amazon-adsystem.com";
    static final String DTB_CONFIG_PATH = "/msdk/getConfig";
    static final int DTB_DOMAIN = 1;
    static final int DTB_GAMMA = 2;
    static final int DTB_PROD = 1;
    static final String DTB_WEB_RESOURCES = "c.amazon-adsystem.com/";
    static final int FIREOS_ADTRACKING_NOT_LIMITED = 0;
    static final String GPS_AVAILABLE_SETTING = "gps-available";
    static final String HTTP = "http://";
    static final String HTTPS = "https://";
    static final String IABCONSENT_CONSENT_STRING = "IABConsent_ConsentString";
    static final String IABCONSENT_SUBJECT_TO_GDPR = "IABConsent_SubjectToGDPR";
    static final String IABTCF_GDPR_APPLIES = "IABTCF_gdprApplies";
    static final String IABTCF_TC_STRING = "IABTCF_TCString";
    static final String INTEGRATED_OM_VERSION = "1_3_28";
    static final int INTERSTITIAL_HEIGHT = 9999;
    static final int INTERSTITIAL_WIDTH = 9999;
    static final String MDTB_NOT_INITIALIZED = "mDTB was not initialized, please use AdRegistration.getInstance(...) before using other SDK calls";
    static final int MEDIATION_ENCODED_PRICE_POINT_LENGTH = 8;
    static final String MEDIATION_NAME = "mediationName";
    static final int NETWORK_READ_TIMEOUT = 60000;
    static final String NETWORK_TYPE_LTE = "13";
    static final String NETWORK_TYPE_UNKNOWN = "0";
    static final String NETWORK_TYPE_WIFI = "Wifi";
    static final String OM_JS_ENDPOINT = "dcqi4aodgg8tv.cloudfront.net/";
    static final String OM_JS_RESOURCE = "resources/omsdk/";
    static final String OM_SDK_DEFAULT_PARTNER_NAME = "Amazon1";
    static final String OM_SDK_PARTNER_KEY_NAME = "omidPartnerName";
    static final String OM_SDK_PARTNER_VERSION_KEY_NAME = "omidPartnerVersion";
    static final String SDK_DISTRIBUTION_KEY_NAME = "distribution";
    static final String SDK_DISTRIBUTION_MARKER_WITH_JSON = "aps_distribution_marker.json";
    static final String SDK_NAME = "Amazon DTB Ads API";
    static final String SDK_VERSION = "9.5.4";
    static final String SDK_VERSION_PREFIX = "aps-android";
    static final long SIS_CHECKIN_INTERVAL = 86400000;
    static String SIS_END_POINT = "s.amazon-adsystem.com";
    static final long SIS_PING_INTERVAL = 2592000000L;
    static final String SIS_SERVER_PATH = "/api3";
    static final String adServerPath = "/e/msdk/ads";
    static final String adVideoServerPath = "/e/vsdk/ads";
    static final String generatePath = "/generate_did";
    static final String pingPath = "/ping";
    static final String sisEndPoint = "s.amazon-adsystem.com/api3";
    static final String updatePath = "/update_dev_info";
}
