package com.explorestack.iab.utils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.util.Base64;

public class Assets {
    public static final int backgroundColor = Color.parseColor("#52000000");
    public static final IabElementStyle defBannerStyle;
    public static final IabElementStyle defCloseStyle;
    public static final IabElementStyle defCountDownProgressStyle;
    public static final IabElementStyle defCountDownStyle;
    public static final IabElementStyle defCtaStyle;
    public static final IabElementStyle defInlineBannerStyle;
    public static final IabElementStyle defLinearProgressStyle;
    public static final IabElementStyle defLoadingStyle;
    public static final IabElementStyle defMuteStyle;
    public static final IabElementStyle defRepeatStyle;
    public static final IabElementStyle defSkipStyle;
    public static final IabElementStyle defTextCountDownStyle;
    public static final IabElementStyle defTextProgressStyle;
    public static final IabElementStyle defVideoStyle;
    public static final int mainAssetsColor = Color.parseColor("#B4FFFFFF");
    public static final int shadowColor = Color.parseColor("#5c000000");

    static {
        IabElementStyle iabElementStyle = new IabElementStyle();
        defCloseStyle = iabElementStyle;
        iabElementStyle.setHorizontalPosition(5);
        iabElementStyle.setVerticalPosition(48);
        Float valueOf = Float.valueOf(2.0f);
        iabElementStyle.setStrokeWidth(valueOf);
        iabElementStyle.setStyle("cross");
        iabElementStyle.setMargin(8, 8, 8, 8);
        Float valueOf2 = Float.valueOf(30.0f);
        iabElementStyle.setWidth(valueOf2);
        iabElementStyle.setHeight(valueOf2);
        Float valueOf3 = Float.valueOf(3.0f);
        iabElementStyle.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle2 = new IabElementStyle();
        defSkipStyle = iabElementStyle2;
        iabElementStyle2.setHorizontalPosition(5);
        iabElementStyle2.setVerticalPosition(48);
        iabElementStyle2.setStrokeWidth(valueOf);
        iabElementStyle2.setStyle("skip");
        iabElementStyle2.setMargin(8, 8, 8, 8);
        iabElementStyle2.setWidth(valueOf2);
        iabElementStyle2.setHeight(valueOf2);
        iabElementStyle2.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle3 = new IabElementStyle();
        defCountDownStyle = iabElementStyle3;
        iabElementStyle3.setHorizontalPosition(5);
        iabElementStyle3.setVerticalPosition(48);
        iabElementStyle3.setStrokeWidth(valueOf);
        iabElementStyle3.setStyle("circular");
        iabElementStyle3.setMargin(8, 8, 8, 8);
        iabElementStyle3.setWidth(valueOf2);
        iabElementStyle3.setHeight(valueOf2);
        iabElementStyle3.setFontStyle(1);
        iabElementStyle3.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle4 = new IabElementStyle();
        defTextCountDownStyle = iabElementStyle4;
        iabElementStyle4.setHorizontalPosition(5);
        iabElementStyle4.setVerticalPosition(48);
        Float valueOf4 = Float.valueOf(16.0f);
        iabElementStyle4.setFontSize(valueOf4);
        iabElementStyle4.setStrokeWidth(valueOf);
        iabElementStyle4.setPadding(12, 2, 12, 2);
        iabElementStyle4.setContent("%1.0f%");
        iabElementStyle4.setStyle("text");
        iabElementStyle4.setMargin(8, 8, 8, 8);
        iabElementStyle4.setFontStyle(1);
        iabElementStyle4.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle5 = new IabElementStyle();
        defMuteStyle = iabElementStyle5;
        iabElementStyle5.setHorizontalPosition(3);
        iabElementStyle5.setVerticalPosition(48);
        iabElementStyle5.setStrokeWidth(valueOf);
        iabElementStyle5.setMargin(8, 8, 8, 8);
        iabElementStyle5.setWidth(valueOf2);
        iabElementStyle5.setHeight(valueOf2);
        iabElementStyle5.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle6 = new IabElementStyle();
        defRepeatStyle = iabElementStyle6;
        iabElementStyle6.setHorizontalPosition(17);
        iabElementStyle6.setVerticalPosition(48);
        iabElementStyle6.setStrokeWidth(valueOf);
        iabElementStyle6.setMargin(8, 8, 8, 8);
        iabElementStyle6.setWidth(valueOf2);
        iabElementStyle6.setHeight(valueOf2);
        iabElementStyle6.setVisible(Boolean.FALSE);
        iabElementStyle6.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle7 = new IabElementStyle();
        defLinearProgressStyle = iabElementStyle7;
        iabElementStyle7.setHorizontalPosition(17);
        iabElementStyle7.setVerticalPosition(80);
        iabElementStyle7.setFillColor(0);
        iabElementStyle7.setStrokeWidth(valueOf3);
        iabElementStyle7.setWidth(-1);
        iabElementStyle7.setHeight(3);
        iabElementStyle7.setStyle("linear");
        iabElementStyle7.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle8 = new IabElementStyle();
        defTextProgressStyle = iabElementStyle8;
        iabElementStyle8.setHorizontalPosition(17);
        iabElementStyle8.setVerticalPosition(80);
        iabElementStyle8.setFontSize(valueOf4);
        iabElementStyle8.setStrokeWidth(valueOf);
        iabElementStyle8.setPadding(12, 2, 12, 2);
        iabElementStyle8.setContent("%1.0f%");
        iabElementStyle8.setStyle("text");
        iabElementStyle8.setMargin(3, 3, 3, 3);
        iabElementStyle8.setFontStyle(1);
        iabElementStyle8.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle9 = new IabElementStyle();
        defCountDownProgressStyle = iabElementStyle9;
        iabElementStyle9.setHorizontalPosition(17);
        iabElementStyle9.setVerticalPosition(80);
        iabElementStyle9.setStrokeWidth(valueOf);
        iabElementStyle9.setOutlined(Boolean.TRUE);
        iabElementStyle9.setStyle("circular");
        iabElementStyle9.setMargin(8, 8, 8, 8);
        iabElementStyle9.setWidth(valueOf2);
        iabElementStyle9.setHeight(valueOf2);
        iabElementStyle9.setFontStyle(1);
        iabElementStyle9.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle10 = new IabElementStyle();
        defCtaStyle = iabElementStyle10;
        iabElementStyle10.setHorizontalPosition(5);
        iabElementStyle10.setVerticalPosition(80);
        iabElementStyle10.setFontSize(valueOf4);
        iabElementStyle10.setStrokeWidth(valueOf);
        iabElementStyle10.setPadding(16, 6, 16, 6);
        iabElementStyle10.setStyle("text");
        iabElementStyle10.setMargin(3, 3, 3, 3);
        iabElementStyle10.setFontStyle(1);
        iabElementStyle10.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle11 = new IabElementStyle();
        defBannerStyle = iabElementStyle11;
        iabElementStyle11.setHorizontalPosition(17);
        iabElementStyle11.setVerticalPosition(80);
        iabElementStyle11.setFillColor((Integer) null);
        iabElementStyle11.setMargin(3, 3, 3, 3);
        IabElementStyle iabElementStyle12 = new IabElementStyle(iabElementStyle11);
        defInlineBannerStyle = iabElementStyle12;
        iabElementStyle12.setMargin((Integer) null, (Integer) null, (Integer) null, (Integer) null);
        IabElementStyle iabElementStyle13 = new IabElementStyle();
        defLoadingStyle = iabElementStyle13;
        iabElementStyle13.setHorizontalPosition(1);
        iabElementStyle13.setVerticalPosition(16);
        iabElementStyle13.setPadding(8, 8, 8, 8);
        iabElementStyle13.setStrokeWidth(valueOf3);
        iabElementStyle13.setWidth(48);
        iabElementStyle13.setHeight(48);
        IabElementStyle iabElementStyle14 = new IabElementStyle();
        defVideoStyle = iabElementStyle14;
        iabElementStyle14.setHorizontalPosition(3);
        iabElementStyle14.setVerticalPosition(48);
        iabElementStyle14.setFillColor(-16777216);
        iabElementStyle14.setStyle("fullscreen");
    }

    public static Bitmap getBitmapFromBase64(String str) {
        byte[] decode = Base64.decode(str, 0);
        return BitmapFactory.decodeByteArray(decode, 0, decode.length);
    }

    public static IabElementStyle resolveDefCloseStyle(Context context, IabElementStyle iabElementStyle) {
        if (iabElementStyle == null || (!"crossfill".equals(iabElementStyle.getStyle()) && !"skipfill".equals(iabElementStyle.getStyle()))) {
            return defCloseStyle;
        }
        IabElementStyle iabElementStyle2 = new IabElementStyle();
        iabElementStyle2.setOutlined(Boolean.TRUE);
        return defCloseStyle.copyWith(iabElementStyle2);
    }
}
