package io.bidmachine.ads.networks.notsy;

interface InternalNotsyInterstitialAdListener extends InternalNotsyAdLoadListener<InternalNotsyInterstitialAd>, InternalNotsyFullscreenAdPresentListener {
}
